### ISSUE TITLE
POST_BUILD example in 03-hello-world-cmake

### ISSUE THREAD

**Issue by bast** [coderefinery/cmake#10]
@blindij I think I see why you want to show it but this might motivate people to do this in their projects. If one needs to change the build directory structure, then this is probably a better way: http://stackoverflow.com/a/6595001

**Comment by blindij** [comment]
My main motivation was to show cmake commands that is cross-platform, but it is very artifical.

**Comment by bast** [comment]
OK good point. Let's keep the cross platform aspect but we need a better example I think.

**Comment by bast** [comment]
How about an example where we create a directory and in it create a file which contains the time stamp of the time we ran the configuration? Later we can build on top of it and improve things and record the git hash etc.

**Comment by blindij** [comment]
Yes, a better idea.

**Comment by bast** [comment]
I think that code is gone in one of the past refactorings and this issue not relevant anymore.
