### ISSUE TITLE
In 02-hello-world.md binary changes between "hello" and "hello.x"

### ISSUE THREAD

**Issue by bast** [coderefinery/cmake#8]
@blindij I would stick with "hello.x" throughout to avoid confusion. It is currently not consistent.

**Comment by blindij** [comment]
The path hello.x - hello - hello.x let me touch upon the implicit rules. I would like to keep it.

**Comment by bast** [comment]
I think the implicit rules are cool to have there. Will it not work with having only "hello.x"? I know too little about the implicit rules but I fear confusion in this example.

**Comment by bast** [comment]
Alternatively we can also switch everything else from hello.x to hello if that helps. But perhaps I simply don't get it :-)

**Comment by blindij** [comment]
You need the additonal rule which I add during the lesson to make it work for hello.x. Initially,I asked that question on Slack, but after having worked with example I understood why. The implicit rule is to make a binary from the stem part of   hello.c, like this : %: %.c

**Comment by bast** [comment]
OK but this to me is a bit confusing:
```
hello.x: hello.cpp
	g++ hello.cpp -o hello
```

I would expect `g++ hello.cpp -o hello.x` - this may make sense further down but at this point it surprised me.

**Comment by blindij** [comment]
You are right, I made an error here. It is g++ hello.cpp -o hello.x

**Comment by bast** [comment]
Issue will go out of scope with #21.

**Comment by bast** [comment]
Issue is not relevant anymore. Closing.
